workflow:
  matrix: &matrix
    # We only test the latest recommended versions here but both template engines
    php: &matrix_php '["8.1"]'
    mysql: &matrix_mysql '["5.7"]'
    # currently, only twig works for oe_vcmsexamples template_engine: &template_engine '["smarty","twig"]'

global:
  git: &git
    shop_ref: &git_shop_ref b-7.0.x
    enterprise_ref: &git_enterprise_ref 'b-7.0.x'

  composer: &composer
    configure:
      ref: &dev_ref dev-b-7.1.x
    require:
      ref: *dev_ref

prepare_shop:
  matrix: *matrix
  git: *git
  composer: *composer

install_shop:
  matrix: *matrix
  git: *git

install_module:
  matrix: *matrix
  cache:
    prefix: 'moduleInstallation-ce-{{ .Github.SHA }}-{{ .Github.RunNumber }}-{{ .Github.RunAttempt }}'
  ids: 'oe_vcmsexamples'
  git:
    module:
      url: &git_module_url '{{ .Github.Repository }}'
      ref: '{{ .Github.Ref }}'
  package_name: &package_name 'oxid-esales/vcms-examples'

codeception_tests:
  matrix: *matrix
  container:
    options: '-e THEME_ID=apex'
  composer: *composer
  configuration: '/var/www/vendor/oxid-esales/vcms-examples/tests/codeception.yml'
  suite: 'acceptance'
  additional_options: '-g oe_vcmsexamples'
  coverage:
    path: ''

shop_setup_tests:
  skip: true

deprecated_tests:
  skip: true

sonarcloud:
  matrix: *matrix
  target_branch: *git_shop_ref
  project_key: 'OXID-eSales_vcms-examples'
  project_name: *package_name
  internal_project_name: ''

phpcs_tests:
  skip: true
  matrix: *matrix

styles:
  skip: false
  matrix: *matrix

finish:
  matrix: *matrix
  slack_title: 'Module oe_vcmsexamples CE on {{ .Github.Repository }} by {{ .Github.Actor }}'
